name: Node.js POST Request Example

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  nodejs-post:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm init -y && npm install axios
      
    - name: Make POST request with Node.js
      run: |
        node -e "
        const axios = require('axios');
        
        async function makePostRequest() {
          try {
            const response = await axios.post('${{ secrets.API_ENDPOINT || 'https://api.beta.blendlabs.com/authentication-status' }}', {
              message: 'Hello from GitHub Action',
              repository: '${{ github.repository }}',
              branch: '${{ github.ref_name }}',
              commit: '${{ github.sha }}',
              actor: '${{ github.actor }}',
              timestamp: new Date().toISOString()
            }, {
              headers: {
                'Content-Type': 'application/json',
                'Authorization': 'Bearer ${{ secrets.API_TOKEN }}'
              }
            });
            
            console.log('Response status:', response.status);
            console.log('Response data:', response.data);
            
            // Check for error messages in response
            if (response.data && response.data.error) {
              console.error('❌ API returned an error:', response.data);
              process.exit(1);
            }
          } catch (error) {
            console.error('Error:', error.message);
            if (error.response) {
              console.error('Response status:', error.response.status);
              console.error('Response data:', error.response.data);
            }
            process.exit(1);
          }
        }
        
        makePostRequest();
        "
        
    - name: POST with fetch (Node.js 18+)
      run: |
        node -e "
        async function makeFetchRequest() {
          try {
            const response = await fetch('${{ secrets.WEBHOOK_URL || 'https://api.beta.blendlabs.com/close/closings?applicationId=aa9fdaa2-7bf3-4411-a836-c2a46117f5c3' }}', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'X-GitHub-Event': '${{ github.event_name }}'
              },
              body: JSON.stringify({
                action: 'workflow_completed',
                repository: '${{ github.repository }}',
                workflow: '${{ github.workflow }}',
                run_id: '${{ github.run_id }}',
                status: 'success'
              })
            });
            
            if (!response.ok) {
              throw new Error(\`HTTP error! status: \${response.status}\`);
            }
            
            const data = await response.json();
            console.log('Webhook response:', data);
            
            // Check for error messages in response
            if (data && data.error) {
              console.error('❌ API returned an error:', data);
              process.exit(1);
            }
          } catch (error) {
            console.error('Error:', error.message);
            process.exit(1);
          }
        }
        
        makeFetchRequest();
        "
