name: Test POST Request

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test-post:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test basic POST request
      run: |
        echo "Testing POST request to httpbin.org..."
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer test-token-123" \
          -d '{
            "message": "Test from GitHub Action",
            "repository": "${{ github.repository }}",
            "branch": "${{ github.ref_name }}",
            "commit": "${{ github.sha }}",
            "actor": "${{ github.actor }}",
            "event": "${{ github.event_name }}",
            "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
          }' \
          "https://httpbin.org/post"
          
    - name: Test form data POST
      run: |
        echo "Testing form data POST..."
        curl -X POST \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "name=Test Action&status=success&repository=${{ github.repository }}&timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
          "https://httpbin.org/post"
          
    - name: Test file upload POST
      run: |
        echo "Testing file upload POST..."
        echo "This is a test file from GitHub Action" > test-file.txt
        echo "Repository: ${{ github.repository }}" >> test-file.txt
        echo "Commit: ${{ github.sha }}" >> test-file.txt
        
        curl -X POST \
          -F "file=@test-file.txt" \
          -F "description=Test file upload from GitHub Action" \
          -F "repository=${{ github.repository }}" \
          "https://httpbin.org/post"
          
        rm test-file.txt
